>CDJ85286.1:7-359 Alcohol dehydrogenase GroES and Alcohol dehydrogenase domain containing protein [Haemonchus contortus]
-RRISLGSPKDLKEVKFFDEEPIPDVPPKGARV--------------KVCYAGVCLTDRE
VTNTKQARVTNGIKDTSLFPGYEVSGVVESFGTESTPEEYDLKIGDKVIVWPTDEMCSHG
YADYVAVPTLHFLVKIPDSLSMHVASILPAGATWALSAVLQARPIVEAFSQSKGFCNILI
VGAGGLGLWLLKLAKHFLVAH---NDKKIRLMVADAKEERLCLAERNGADFVVHWDDSEF
EEYLIMRTKDVARTGVNVVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKLVA
KNRLAIMGVTRGSIEQLKNLVHLIAGGQIEAPDYVVYPVNQASQVLKQLSMSEVEGRAIL
EVCDPNAALDL-----
>OUC41321.1:1-359 GroES-like protein [Trichinella nativa]
MRRLSLGSPKDLKEVHFFNDVPLPKVPPNGARI--------------KVCYAGVCLTDQE
VMKNSKIRITCGIKDTSLFPGFEVSGVIESIGSNAKAAEFNLKVGDRVVVWPSEEMAKCG
YADLISVPHLEDLIKVPDSFSMSVAAMLPAGATWAYAAAMQSLQTVEAVLRTQSRCNLLI
VGAGGLGLWLLKMCKYYLGANG---ERPVTILVADGKEERLSLAERNGADCVVHWDESEF
EQTLITRTKDAARSGLQIIFDFVTSPRTVTRSLHCLADGGVLYIGGLSGVDIQLSVKLLA
QKRLSIVGVSRGSVELLQDLVNLISQGQLEPPTYKVYPVGQAGEVLKQLSMSELEGRAIL
EVCDTDRAVSMVQFPS
>XP_003100702.1:6-358 hypothetical protein CRE_15539 [Caenorhabditis remanei]
-RRISLGSPKDLREVKFFDEEPIPDVPPKGARV--------------KVCYAGVCLTDRE
VSNTKQARITNGIKDTSLFPGYEVSGIVESFGSECTPRDYDLNIGDKVIVWPTDEMCSHG
YADYVAVPTLHFLVKIPETLSMHVASILPAGATWALSAVLQARPIVEAFSQSKGFCNILI
VGAGGLGLWLLKLAKHFLAIN---NDKKIRLMVADAKEERLSLAERNGADFVVHWDDSEF
EEYLIMRTKDVARTGVNVVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKHVA
KNRLAIMGVTRGSIEQLKNLVNLIAGGQIDAPDYRVYPVDQASAVLKQLSMSEVEGRAIL
EVCDPISALNI-----
>KAJ1360648.1:26-377 hypothetical protein KIN20_019674 [Parelaphostrongylus tenuis]
-RRISLGSPKDLKEVKFFDEEPIPDVPPKGARV--------------KVCYAGVCLTDRE
VTNTKQARITNGIKDTSLFPGYEVSGVVESFGNQASPDEYDLKIGDKVIVWPTDEMCSHG
YADFVAVPTLQFLVKIPDSLSMHVASILPAGATWALSAVLQARPIVEAFSQSKGFCNILI
VGAGGLGLWLLKLAKHFLVFH---NDKKIRLMVADAKEERLCLAEKNGADFVVHWDDSEF
EEYLIMRTKDVARTGVNVVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKLVA
KNRLAIMGVTRGSMEQLKNLVHLIAGGQIEAPDYRVFPVAQASQVLKQLSMSELEGRAIL
EVCDPKTALT------
>EYC13571.1:7-352 hypothetical protein Y032_0043g792 [Ancylostoma ceylanicum]
-RRISLGSPKDLKEVKFFDEEPIPDVPPKGARV--------------KVCYAGVCLTDRE
VTNTKQARVTNGIKDTSLFPGYEVSGVVESFGSECTPDEYDLKIGDKVIVWPTDEMCSHG
YADYVAVPTLHFLVKIPDTLSMHVASILPAGATWALSAVLQARPIVEAFSQSKGFCNILI
VGAGGLGLWLLKLAKHFLVSH---NDRKIRLMVADAKEERLCLAERNGADFVVHWDDSEF
EEYLIMRTKDVARTGVNVVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKLVA
KNRLAIMGVTRGSIEQLKNLVHLIAGGQIDAPDYRVYPVNQASQVLKQLSMSEVEGRAIL
EVCD------------
>KAI6219995.1:10-369 PKS-ER domain-containing protein [Aphelenchoides besseyi]
-RRILLGSVDDLRHVELLEEQKLPEVPSLGCRIRVSSLVTETRQLDFQVCYVGACLADGE
NSRKHRPRLVSGIKNCSLYSGYELSGIIESFGSDVKTANLEFAIGDRVVVWPTNEMREFG
YADFVCCPDLKLIIKIPETVSMPVSSMLSTSATYAMSAITQALPFVESLIIKSGYCNVLI
IGAGALSLWLLTLAKQILAQN---KGRRVKIYIADSKEDRLRQAENSGADGAIEWDDGQF
EQYLIMRTKNAAARGVHIIFDCVSSTRTVDRSLNCLAENGILFVGGLAGTKVQLPVNLMC
ENGLSVQGIKRGTFENLRQLMAMIERGEIEVPDYSVYPVDEAVKVMQQMSAGELDGRTIL
EVWD------------
>VDM26094.1:3-322 unnamed protein product [Toxocara canis]
--------------------------------L--------------KVCYAGVCLTDRE
VTNTKQARITNGIKDTSLFPGYEVSGVVEAFGDETNAAEFDLKIGDKVIVWPTDEMCQHG
YADYVTVPTLQFLIKIPDTLSMHVASILPAGATWALSAVIQARPIVEAFSQSKGFCNILI
VGAGGLGLWLLKLAKHFLSGQ---QDRKIKIMVADGREERLCLAERNGADFVVHWDDSEF
EEYLIMRTKDVARTGVQVVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKLVA
RNRLAIMGVTRGSIEQLKNLVCLIAGGQIDAPDYRVYPVNQASQVLKQLSMSEVEGRAIL
EVCDPNTAL-------
>KAI1733276.1:10-361 zinc-binding dehydrogenase domain-containing protein [Ditylenchus destructor]
-RRISLGSPKDLKEVHFFEEEEIPDVPLKGARV--------------KVCYAGVCLTDRE
ITNTKQARITNGVKDTSLFPGYEVSGVVESFGAEAKAEEFNLHIGDKVIVWPTDEMCQHG
YADYVSVPNLELLVKIPDTLSMHVASILPAGATWALSAVVHARPIVEALSASKGYCNILI
VGAGGLGLWLLKLAKHFLAGGGAQEHAKIKVMVADGKEERLCLAERNGADFVVHWDDSEF
EEYLIMRTKDVARTGVQIVFDFVTSPRTVTRSLKCLAEGGVLFVGGLSGLDVQLPIKLVA
KNRLAIMGVSRGSIDQLKSLVCLIADGQIEAPDYRVYPVNQASHVLKQLSMSELEGRAIL
EVFDPDK---------
