# TO DO: ADD YOUR HEADER COMMENT HERE

# TO DO: IMPORT NEEDED MODULE(S)
 
# TO DO: DEFINE REQUIRED FUNCTIONS - EACH FUNCTION MUST HAVE A COMMENT / DOCSTRING
        
if __name__ == "__main__":
    # TO DO: WRITE THE MAIN ROUTINE HERE