% By: Corine Lontoc, Soham Patel, Sam Schonwald

function [] = ImportData(user, date, height, weight, sputum_color, ...
                stool_consist, stool_color, cough_freq, ...
                effort_breath, level_activity, amount_sputum, ...
                stomach_pain, appetite_level)
%IMPORTDATA used to put survey results into an SQL database

% save survey results
datatable = table(user, date, height, weight, sputum_color, ...
                stool_consist, stool_color, cough_freq, ...
                effort_breath, level_activity, amount_sputum, ...
                stomach_pain, appetite_level);


% dbfile saves file path for the symptoms
%dbfile = fullfile(pwd,'User_Database.sqlite');
dbfile = [bmes.tempdir() '/User_Database.sqlite'];

% Conn establishes connection to database
conn = sqlite(dbfile);

% Create table in which to load results
exec(conn, ['CREATE TABLE IF NOT EXISTS symptoms ' ...
    '(user VARCHAR(30),' ...
    'date VARCHAR(30),' ...
    'height FLOAT(3,2), ' ...
    'weight FLOAT(3,2),' ...
    'sputum_color VARCHAR(30),' ...
    'stool_consist VARCHAR(30),' ...
    'stool_color VARCHAR(30),' ...
    'cough_freq FLOAT(2,2),' ...
    'effort_breath FLOAT(2,2),' ...
    'level_activity FLOAT(2,2),' ...
    'amount_sputum FLOAT(2,2),' ...
    'stomach_pain FLOAT(2,2),' ...
    'appetite_level FLOAT(2,2))'])

% Isfile checks for the SQL file, if not created, then create
% Conn establishes connection to database
conn = sqlite(dbfile);

% sqlwrite puts data into the SQL table
sqlwrite(conn, 'symptoms', datatable);

end

